### ISSUE TITLE
Why `js-success`?

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next#2]
We have this in all of our apps (engels, dobi, grumman) but have never used it.
```sh
mandrews@matt ~/sandboxes/next-dobi (tidy-layout) $ ag js-success
views/layout.html
56:				document.documentElement.classList.add('js-success');
mandrews@matt ~/sandboxes/next-dobi (tidy-layout) $ cd ../next-dobi/
mandrews@matt ~/sandboxes/next-dobi (tidy-layout) $ ag js-success
views/layout.html
56:				document.documentElement.classList.add('js-success');
mandrews@matt ~/sandboxes/next-dobi (tidy-layout) $ cd ../next-e
-bash: cd: ../next-e: No such file or directory
mandrews@matt ~/sandboxes/next-dobi (tidy-layout) $ cd ../next-engels/
mandrews@matt ~/sandboxes/next-engels (tidy-layout) $ ag js-success
views/layout.html
30:				document.documentElement.classList.add('js-success');
```

What do we think we should do? Delete it? Start using it?

@commuterjoy @wheresrhys @aintgoin2goa

**Comment by matthew-andrews** [comment]
@leanne1 @adgad

**Comment by wheresrhys** [comment]
this was useful in fastft's end to end tests: if js-success class isn't
present then js hasn't loaded correctly so fail immediately and avoid loads
of noisy failures from each feature X not working. Also, for web driver at
least, it provided a very useful hook to know when page is ready to start
running tests

On 2 January 2015 at 11:16, Matt Andrews <notifications@github.com> wrote:

> @leanne1 <https://github.com/leanne1> @adgad <https://github.com/adgad>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next/issues/2#issuecomment-68520232>.
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by matthew-andrews** [comment]
@wheresrhys makes sense.  see now harm to leave in.
