### ISSUE TITLE
Should we use `--harmony` and start using ES6 server side?

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next#3]
cc @commuterjoy @leanne1 @adgad @wheresrhys @aintgoin2goa @richard-still-ft

**Comment by matthew-andrews** [comment]
It would allow us to solve [this](https://github.com/Financial-Times/next-feature-flags-client/issues/26)

**Comment by aintgoin2goa** [comment]
I think there is a specific --harmony_proxies flag or similar if you want proxies, there's a few others too - maybe we should turn on features as and when we need them?

Regarding proxies I've been fiddling around with them in firefox over the last couple of weeks and it seems a bit unstable/buggy at the moment - I think what you're proposing would be ok, though.

I be worried about relying on on a experimental technology for something so fundamental - do we know anything about performance of proxies?
