### ISSUE TITLE
Next naming convention

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next#38]
For things that are solid and stable is it time to graduate to sensible names?

```
next-engels => next-home
next-grumman => next-article
```

I think dobi can stay for now because I think we may split search out.

cc @ironsidevsquincy @keirog @i-like-robots @kaelig @adambraimbridge @aintgoin2goa @adamsilver @wheresrhys @adgad @commuterjoy @tom-parker

**Comment by kaelig** [comment]
:v:

**Comment by matthew-andrews** [comment]
Seeing how difficult this is here:-
https://github.com/Financial-Times/next-grumman/pull/455

**Comment by i-like-robots** [comment]
It would definitely help orientate new people like me =)

**Comment by ironsidevsquincy** [comment]
And people who have been here 3 months

**Comment by commuterjoy** [comment]
Good idea.

Ideally we wouldnt break the graphite names during any renaming.

**Comment by matthew-andrews** [comment]
> Ideally we wouldnt break the graphite names during any renaming.
it would be like a new app…?

**Comment by matthew-andrews** [comment]
Politely pinging @tom-parker  :-)

**Comment by adambraimbridge** [comment]
Plusone
On 15 Jun 2015 8:50 pm, "Matt Andrews" <notifications@github.com> wrote:

> Politely pinging @tom-parker <https://github.com/tom-parker> :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next/issues/38#issuecomment-112186980>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by tom-parker** [comment]
Current naming conventions are listed here -

http://financial-times.github.io/next/docs/developer-guide/naming-conventions/

Should we change this?

**Comment by matthew-andrews** [comment]
I can't remember who suggested it but I quite like this idea:-
https://github.com/Financial-Times/next/pull/51

And the badgers have also started using this :smile:
