### ISSUE TITLE
Deprecate ft-api-client

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next#74]
We have two API clients:
- [next-ft-api-client](https://github.com/Financial-Times/next-ft-api-client)
- [ft-api-client](https://github.com/Financial-Times/ft-api-client)

Maintaining both is very confusing! The former can speak to ES but the latter cannot.

I propose we deprecate and migrate away from ft-api-client. [Here are the apps using (all manner of versions of) ft-api-client](https://github.com/search?l=json&q=ft-api-client+user%3AFinancial-Times&ref=searchresults&type=Code&utf8=%E2%9C%93).

**Comment by matthew-andrews** [comment]
oh man…
