### ISSUE TITLE
Cleanup dotfiles

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next#78]
Some of our apps expect one or a couple of dotfiles to be present in a user's home directory which is confusing and unnecessary. NBT should be used to download and store keys.

- [ ] [.nextElasticSearchUrl](https://github.com/search?utf8=%E2%9C%93&q=..nextElasticSearchUrl+user%3AFinancial-Times&type=Code&ref=searchresults)
- [ ] [.elastic_search_host](https://github.com/search?utf8=%E2%9C%93&q=.elastic_search_host+user%3AFinancial-Times&type=Code&ref=searchresults)

**Comment by matthew-andrews** [comment]
they should all use NBT's environment variables and use neither.

**Comment by i-like-robots** [comment]
Updated the issue to cover dotfiles in general
